.TH "patcher" "1" "Sept 25 2003" "" ""
.SH "NAME"
patcher
.SH "SYNOPSIS"
.PP
patcher from-file [-f format] patch [extra patches] to-file
.PP
.SH "DESCRIPTION"
patcher is a program for reconstructing a file based off of a reference file 
and at least one patch\&.
.SH "OPTIONS"
.PP
.nf

-V, --version                   output version, and exit
-v, --verbose                   increase verbosity
-c, --to-stdout                 output to-file to stdout
-f, --patch-format FORMAT       used to override the auto
                                identification of a patch's format\&.
                                Valid formats are-
                                bdelta, gdiff4, gdiff5 (a nonstandard 
                                modification to gdiff4), bdiff, xdelta
                                and switching\&.
                                This option is not normally needed, 
                                since patcher can identify a patch's
                                format automatically if it is 
                                supported\&.
.fi
.PP
.SH "SEE ALSO"
.PP
differ(1)
diffball(1)
convert_delta(1)
.PP
.SH "BUGS"
none known
.PP
.SH "VERSION"
.PP
This man page is current for version 0&.7&.1 of patcher
.PP
.SH "CREDITS"
patcher, and by extension the diffball suite, is distributed under the GNU 
public license\&.  The file COPYING contains the details\&.
.PP
.SH "AUTHOR"
patcher was written by Brian Harring <ferringb@gmail&.com>
