#!/usr/bin/perl
use POSIX qw (ceil);
use Fcntl;
open(my $fh1, $ARGV[0]) or die("shite, couldn't fine ".$ARGV[0]."\n");
binmode($fh1);
my $file1;
my @returns;
my @labels= (
	'name', 'mode', 'uid', 'gid', 'size', 'mtime', 'chksum', 'typeflag', 'linkname', 'magic','version','uname','gname',
	'devmaj','devmin','prefix');
my $tar_unpack_header= 'A100 A8 A8 A8 A12 A12 A8 A1 A100 A6 A2 A32 A32 A8 A8 A155 x12';
my $temp;
my $loc=0;
my $seek=0;
my @locs;
while(sysread($fh1, $temp,512) && $temp ne ''){
	push(@locs, $offset);
	$offset +=512;
	my @array = unpack($tar_unpack_header, $temp);
	foreach my $num (1,2,3,4,5,6,13,14) {
		$array[$num] = oct($array[$num]);
	}
#	print "size=".$array[4]."\n";
	$seek= ( ceil($array[4]/512) * 512);
	$offset += $seek;
	sysseek($fh1, $seek, 1);
	push(@returns, \@array);
}
$_=length($returns[0][0]);
my $size=length($_)+6;
for(my $y=0; $y<scalar(@returns); $y++){
	if ($ARGV[1] =~/-c/i) {system('clear');}
	print "----------------------------------------------------------------------------------\n";
	printf("%${size}s:'%i'\n", 'entry', $y);
	printf("%${size}s:'%i -> %i'\n", 'loc', $locs[$y]/512, $locs[$y]);
	for(my $x=0; $x<scalar(@{$returns[$y]});$x++){
		if ($x==0) {
			printf("%${size}s:'%s'\n", sprintf("%s(%s)",$labels[$x], length($returns[$y]->[0])), $returns[$y]->[0]);
		} else {
			print sprintf("%${size}s",$labels[$x]).":'".$returns[$y]->[$x]."'\n";
		}
	}
}
