#!/usr/bin/perl
#use strict;
my @array = @ARGV;
my $print_char = 0;
my $start_off =0;
my $limitcount = 0;
my $file='';
my $x;
for($x=0; $x < scalar(@array); $x++) {
	if($array[$x]=~/^-c$/i) {
		$print_char = 1;
#		splice(@array, $x, 1);
	} elsif($array[$x]=~/^-s(\d+)$/) {
		$start_off = $1;
#		splice(@array, $x, 1);
	} elsif($array[$x]=~/^-e(\d+)$/i) {
		$limitcount = $1;
	} else {
		$file = $array[$x];
	}
}
open(my $fh, $file) or die("Couldn't open $file!\n");
my $nolimit = $limitcount eq 0 ? 1 : 0;
my $count=$start_off;
my $char;
sysseek($fh, $start_off, SEEK_SET);
for($x=0; sysread($fh, $char, 1) && ($x < $limitcount || $nolimit); $x++) {
	#sysread($fh, $char, 1);
	if(($count - $start_off) % 8==0) {
		#$count=0;
		print "\n$count:";
	}
	if($print_char) {
		printf(" %1.1s=%02x ", chr(ord($char)), ord($char));
	} else {
		printf(" %03.3s=%02x ", ord($char), ord($char)); 
	}
	$count++;
}
print "\n";
