#!/usr/bin/perl
my @array = @ARGV;
my $print_char = 0;
for($x=0; $x < scalar(@array); $x++) {
	if($array[$x]=~/-c/i) {
		$print_char =1;
		splice(@array, $x, 1);
	}
}
open(my $fh, $array[0]) or die("Couldn't open $array[0]!\n");
my $nolimit = $array[1] eq '' ? 1 : 0;
my $limitcount = $array[1] eq '' ? 0 : $array[1];
my $count=0;
my $char;
if($array[2] ne '') {
	sysseek($fh, $array[2], SEEK_SET);
}
for($x=0; sysread($fh, $char, 1) && ($x < $limitcount || $nolimit); $x++) {
	#sysread($fh, $char, 1);
	if($count==8) {
		$count=0;
		print "\n";
	}
	if($print_char) {
		printf(" %1.1s=%02x ", chr(ord($char)), ord($char));
	} else {
		printf(" %03.3s=%02x ", ord($char), ord($char)); 
	}
	$count++;
}
print "\n";
